// Some DAO's have different id from twitter handle
const twitterIdMap = {
  juiceboxeth: 'juicebox',
  dune_dao: 'dunedao',
  thepeopledaoorg: 'thepeopledao',
  landbackdao: 'landback',
  demuapp: 'demu',
  illuminati_dao: 'illuminatidao',
  lifedao_: 'lifedao',
  pixdaoeth: 'pixdao',
  july_fourthdao: 'julyfourthdao',
  perceptforminc: 'perceptform',
  auroraisnear: 'auroradao',
  kanyedao: 'kanyebeardao',
  profootballdao: 'footballdao',
  marsownership: 'marsownershipdao',
  dreamdaomoney: 'dreamdao',
  scorpio_vc: 'scorpiodao',
  nftsalphas: 'nftalphadao',
  rainbowwallpro: 'rainbowwalldao',
  copydao17: 'copydao',
  thehashworld: 'hashworld',
  givingtuesday: 'kimbal',
  ethmovie: 'theinfinitemachinemovie',
  drprocrast: 'junglemedicalaiddao',
  missapeworlds: 'missapeyachtclub',
  ajeffersondao: 'jeffersondao',
  beetsdao: 'eyez',
  people_angeldao: 'peopleangelsdao',
  tile_dao: 'tiles',
  ethsidemafia: 'nftbluechipsdao',
  thespicedao: 'spicedao',
  merge_dao: 'mergedao',
  shawnmeluni: 'translatordao',
  '0xshibboleth': 'hanukkahdao',
  thetangdao: 'tangdao',
  thegrantsdao: 'grantsdao',
  nftafrika: 'projectnftafrica',
  ponzi_dao: 'ponzidao',
  officialmoondao: 'moondao',
  canu_dao: 'canudaocomm',
  slice__so: 'slice',
  thewhiskydao: 'whiskydao',
  daoimmortal: 'immortaldao',
  meatsacksc: 'shielddao',
  crayonfinance: 'heritagedao',
  simulationdao: 'thesimulation',
  defikingdomsdao: 'defikingdomsguild',
  thedomaindao: 'domaindao',
  _helpuk: 'helpdao',
  santadao__: 'santa',
  pizzadao2010: 'pizzadao',
  dogekingst: 'dogeking',
  treesmoretrees: 'treeslotsoftrees',
  theone_dao: 'theonedao',
  sifu_dao: 'sifudao',
  ahenk75752813: 'csale',
  pandao_official: 'pandadao',
  johnnyd_eth: 'johnnydao',
  'thebattle.com': 'battletest',
  experimintdao: 'experimint',
  realgolddao: 'golddao',
  rainbow__dao: 'rainbow',
  thejosedao: 'josedao',
  las_daofficial: 'lifeisastruggledao',
  satrabrunn: 'satrabrunndao',
  poap_dao: ' poapdao',
  myspacedao: 'spacedao',
  bitmousedao_: 'bitmousedao',
  baohudao: 'baohu',
  dao_philosophy: 'philosophydao',
  exposain_: 'exposain',
  ganjamecca: 'ganja',
  theburgerdao: 'burgerdao',
  lunar_dao: 'lunardao',
  thebeardao_: 'beardao',
  kyrie_dao: 'kyriedao',
  satoshiisfemale: 'satoshiisfemale01dao',
  jukeboxdao: 'jukebox',
  helladopenyc: 'helladope',
  thewell813: 'wellbuiltcity',
  moon3dio: 'moon3d',
  blablablock2021: 'blablablock',
  watchdao_: 'watchdao',
  projectdaonow: 'projectdao',
  metamask_dao: 'metamaskdao',
  kiterun27079407: 'kiterunner',
  gdng17829035: 'goudenage',
  climateactndao: 'climateactiondao',
  undermine_vc: 'undermine',
  nepridao_hq: 'nepridao',
  thepiecedao: 'piecedao',
  benepubblicobrm: 'benepubblicobrmoro',
  theblockonomist: 'blockonomist',
  landmarketdao: 'lotf',
  novel_dao: 'noveldao',
  gaetano9910: 'hackataolongterm',
  pandoralandpgd: 'pandoraland',
  lost_artifacts: 'lostartifacts',
  daohubofficial: 'daohubonbsc',
  et_dao: 'etdao',
  loser__dao: 'loserdao',
  blimp_dao: 'blimpdao',
};

const ignoreProjects = ['spe_bsc_token', 'booknerd_eth'];

module.exports = {
  twitterIdMap,
  ignoreProjects,
};
