// Some DAO's have different id from twitter handle
const twitterIdMap = {
  juiceboxeth: 'juicebox',
  dune_dao: 'dunedao',
  thepeopledaoorg: 'thepeopledao',
  landbackdao: 'landback',
  demuapp: 'demu',
  illuminati_dao: 'illuminatidao',
  lifedao_: 'lifedao',
  pixdaoeth: 'pixdao',
  july_fourthdao: 'julyfourthdao',
  perceptforminc: 'perceptform',
  auroraisnear: 'auroradao',
  kanyedao: 'kanyebeardao',
  profootballdao: 'footballdao',
  marsownership: 'marsownershipdao',
  dreamdaomoney: 'dreamdao',
  scorpio_vc: 'scorpiodao',
  nftsalphas: 'nftalphadao',
  rainbowwallpro: 'rainbowwalldao',
  copydao17: 'copydao',
  thehashworld: 'hashworld',
  givingtuesday: 'kimbal',
  ethmovie: 'theinfinitemachinemovie',
  drprocrast: 'junglemedicalaiddao',
  missapeworlds: 'missapeyachtclub',
  ajeffersondao: 'jeffersondao',
  beetsdao: 'eyez',
  people_angeldao: 'peopleangelsdao',
  tile_dao: 'tiles',
  ethsidemafia: 'nftbluechipsdao',
  thespicedao: 'spicedao',
  merge_dao: 'mergedao',
  shawnmeluni: 'translatordao',
  '0xshibboleth': 'hanukkahdao',
  thetangdao: 'tangdao',
  thegrantsdao: 'grantsdao',
  nftafrika: 'projectnftafrica',
  ponzi_dao: 'ponzidao',
  officialmoondao: 'moondao',
  canu_dao: 'canudaocomm',
  slice__so: 'slice',
  thewhiskydao: 'whiskydao',
  daoimmortal: 'immortaldao',
};

module.exports = {
  twitterIdMap,
};
