name: Crawl every hour

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: master
      - uses: pnpm/action-setup@v2
        with:
          version: '6.23.1'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Cache info files
        uses: actions/cache@v2
        id: info-cache
        with:
          path: |
            .cache
          key: NO_CHANGE

      - name: pnpm install
        run: pnpm i

      - name: Crawl
        run: |
          pnpm crawl
          pnpm build

      - name: Git Diff
        id: git-diff
        if: success()
        run: |
          echo "GIT_DIFF<<EOF" >> $GITHUB_ENV
          git diff development/com.maskbook.dao-* | head -n 200 >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Commit changes
        if: ${{ env.GIT_DIFF != '' }}
        run: |
          git add .
          git config --local user.email "bot@mask.io"
          git config --local user.name "commit bot"
          git commit -m "`date '+chore: crawl dao data from juicebox at %Y-%m-%d %H:%M'`"
          git push origin master
