name: Crawl every hour

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: master
      - uses: pnpm/action-setup@v2
        with:
          version: '6.23.1'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Cache info files
        uses: actions/cache@v2
        id: info-cache
        with:
          path: |
            .cache
          key: NO_CHANGE

      - name: pnpm install
        run: pnpm i

      - name: Crawl
        run: pnpm crawl

      - name: Get Changes
        run: |
          echo "DIFF_STAT<<EOF" >> $GITHUB_ENV
          echo "## Updates" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "\`\`\`" >> $GITHUB_ENV
          git diff --stat ':(exclude).github' ':(exclude)scripts' >> $GITHUB_ENV
          echo "\`\`\`" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ':chore: crawling updates'
          committer: Maskbook maintainer bot <bot@mask.io>
          author: Maskbook maintainer bot <bot@mask.io>
          branch: auto-crawl
          title: ':chore: crawling updates'
          body: "## (🤖 I am a robot) updates or error report \n```${{ env.DIFF_STAT }}\n```\n\n"
          assignees: |
            guanbinrui
            unclebill
          draft: false
